[package]
name = "system-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.11.0"
sysinfo = "0.29.9"

[dev-dependencies]
anyhow = "1.0.75"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
